#!/bin/bash

# Find the root htdocs dir
arr=$(pwd | tr "/" "\n")

n=3
a=0
k=''

for x in ${arr[@]}
do
if [ $a -gt "$n" ]
then
 break;
fi

k="${k}/${x}"
a=$(($a+1))

done

k="${k}/htdocs"

# Establish the owner
owner=`stat -c %U ${k}`

chown -R ${owner}:www-data $k 
find $k -type d -exec chmod 770 {} \;
find $k -type f \! -executable -exec chmod 660 {} \;
find $k -type f -executable -exec chmod 770 {} \;
