#!/bin/bash
# 
# VPS to Dropbox/AeroFS Backup Script
#
# by Rares Cosma - rares@getbetter.ro
# http://www.rarescosma.com
#

# Path
export PATH=$PATH:/usr/local/bin

# Config
BIN_DEPS="curl sed grep tr date p7zip drop"
VERSION="0.4"

# VPS
V_EXCLUDED_DOMAINS="/usr/local/dev/excluded.domains"
V_SITES_PATH="/var/www/virtual/"
V_BACKUP_PATH="/backup/"
V_BACKUP_COMMAND="/var/www/ispcp/engine/backup/ispcp-backup-all yes"
V_BACKUP_LOCK_FILE="/tmp/ispcp-backup-all.lock"


# Functions
usage()
{
	echo "Usage: $0 [-b | -m | -d]"
}

d_upload()
{
	UPLOAD_FILE=$1
	UPLOAD_DIR=$2
	
	/usr/local/bin/drop upload $UPLOAD_FILE $UPLOAD_DIR &>/dev/null
}

m_backup()
{
	# Perform Backups
	rm -rf $V_BACKUP_LOCK_FILE
	$V_BACKUP_COMMAND
	rm -rf $V_BACKUP_LOCK_FILE
}

m_move()
{
	# Cleanup the destination
	rm -rf ${V_BACKUP_PATH}/*

	# Process all domains
	for i in ${V_SITES_PATH}*; do
		domain=${i:${#V_SITES_PATH}:${#i}};
		go=1;
		while read LINE; do
			LINE=`echo $LINE | tr -d "\n"`
			if [ "$LINE" == "$domain" ]
			then
				go=0;
			fi
		done < $V_EXCLUDED_DOMAINS
		if [ "1" == "$go" ]
		then
		for j in `find ${V_SITES_PATH}${domain}/backups/*.tar ${V_SITES_PATH}${domain}/backups/*.sql.gz 2>/dev/null`; do
			k=${j##*/}
			mkdir -p ${V_BACKUP_PATH}${domain}
			DEST=${V_BACKUP_PATH}${domain}/${k}
			mv $j $DEST
			chmod 660 $DEST
			chown karelian:www-data $DEST
		done
		echo "Backed up ${domain}"
		fi
	done
	m_zip
}

m_zip()
{
	for i in `find ${V_BACKUP_PATH} -type f -name "*.tar"`; do
                p7zip $i &>/dev/null
        done;
}

m_drop()
{
	# Initialize Dropbox
	#d_init

	# Get the weekday
	WDAY=`date +%u | tr -d "\n"`

	for i in ${V_BACKUP_PATH}*; do
		domain=${i:${#V_BACKUP_PATH}:${#i}};
		DEST_PATH=Dev/VPS/${domain}/${WDAY};

		for j in `find $i -type f`; do
			d_upload $j $DEST_PATH/$(basename $j)
		done
		echo "Uploaded ${domain} to Dropbox";
	done
}


m_aero()
{
        # Get the weekday
        WDAY=`date +%u | tr -d "\n"`

        for i in ${V_BACKUP_PATH}*; do
                domain=${i:${#V_BACKUP_PATH}:${#i}};
                DEST_PATH=/home/karelian/AeroFS/VPS/${domain}/${WDAY};

		mkdir -p $DEST_PATH

                for j in `find $i -type f`; do
			cp $j $DEST_PATH/$(basename $j)
                done

                echo "Uploaded ${domain} to AeroFS";
        done

	chown -R karelian:karelian /home/karelian/AeroFS/VPS
}
	
# Check Dependencies
for i in $BIN_DEPS; do
	which $i > /dev/null
	if [ $? -ne 0 ]; then
		echo "Error: Required dependency could not be found: $i"
		exit 1
	fi
done

# Process Command Line
if [ $# -eq 0 ]; then
	usage
	exit 1
fi

while [ "$1" != "" ]; do
	case $1 in
		-a | --all )
			echo
			echo `date` 
			m_backup
			m_move
			m_drop;;
		-z | --zip )
			m_zip;;
		-b | --backup )
			m_backup;;
		-m | --move )
			m_move;;
		-d | --drop )
			m_drop;;
		--aero )
			m_aero;;
		-h | --help )
			usage
			exit;;
		* )
			exit 1
	esac
	shift
done
