#!/bin/bash

DEBUG=0
DEPLOY_PATH=/usr/local/bin/
FILES=`find \`pwd\` -type f \
		\( ! -iname "_*" ! -iname ".*" ! -iname "*.md" \)`

for source in $FILES;
do
	dest=`echo $DEPLOY_PATH$(basename $source) | sed 's/\[\([^]]*\)\]//g'`

	if [[ $DEBUG -eq 1 ]]
	then
		echo $source;
		echo $dest;
	else
		ln -sf $source $dest
	fi

done;
