#!/usr/bin/perl

use strict;
use warnings;

sub rares_in_array {
    my ($arr,$search_for) = @_;
    return grep {$search_for eq $_} @$arr;
}

my $arr = ["forwardinasdc.com", "getbetter.ro"];

if ( rares_in_array($arr, "forwardinc.com") ) {
 print "yay";
}
