#!/bin/bash

# Bailout if file doesn't exist
if [ ! -f $1 ];
then
	FULL_PATH=''
else
	FULL_PATH=$(cd $(dirname "$1") && pwd -P)/$(basename "$1")
	FULL_PATH="Z:`echo $FULL_PATH | sed -e 's/\//\\\\\\\\/g'`"
fi

env WINEPREFIX="/home/karelian/.local/share/wineprefixes/irfanview" >/dev/null 2>/dev/null
wine /home/karelian/.local/share/wineprefixes/irfanview/drive_c/Program\ Files/IrfanView/i_view32.exe $FULL_PATH >/dev/null 2>/dev/null
