#!/bin/bash

chown -R karelian:www-data ./ 
find ./ -type d -exec chmod 770 {} \;
find ./ -type f -exec chmod 660 {} \;
#find $k -type f -print | grep -v "/\." | perl -lne 'print quotemeta' | xargs chmod 660
