#!/bin/bash

dname=
while [[ $dname = "" ]]; do
    echo -n "Enter site name (domain.com): "
    read dname
done

if [ -x /var/www/$dname ]; then
    # Disable site
    a2dissite $dname
    service apache2 restart

    # Remove files
    rm -rf /var/www/$dname

    # Remove database
    dbname=`echo $dname | sed 's/\./_/g'`
    mysql -u root -e "drop database $dbname;"

    # Remove available-site
    rm -rf /etc/apache2/sites-available/$dname

    # Remove hosts entry
    ename=`echo "$dname" | sed 's/\./\\\\./g'`
    sed -i_bak -e "/$ename/d" /etc/hosts
fi